# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehubcreateeventmodel',
            name='event_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
