# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='image_file',
            field=models.FileField(blank=True, upload_to='blog_images/'),
        ),
    ]
