# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codehubtopicmodel',
            old_name='uploaded_file',
            new_name='file',
        ),
    ]
