# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160406_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehubtopicmodel',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
