# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_codehubcreateeventmodel_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user', models.CharField(max_length=10)),
                ('following_user_profile', models.CharField(max_length=10)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followed_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfileModel')),
            ],
        ),
    ]
