# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdetailsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetailsModel',
            new_name='UserProfileModel',
        ),
    ]
