# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_codehubtopiccomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodehubTopicComments',
            new_name='CodehubTopicCommentModel',
        ),
    ]
