# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160403_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehubcreateeventmodel',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
