# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_followusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followusermodel',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followusermodel',
            name='followed_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_profile', to='app.UserProfileModel'),
        ),
        migrations.AlterField(
            model_name='followusermodel',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followusermodel',
            name='following_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user_profile', to='app.UserProfileModel'),
        ),
    ]
