# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:11
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160406_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehubcreateeventmodel',
            name='event_description',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
