# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160401_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_type_select',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
