# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogpostcommentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcommentmodel',
            old_name='blog',
            new_name='blog_post',
        ),
    ]
