# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20160402_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodehubClassTalkNotifiyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_heading', models.CharField(max_length=100)),
                ('class_on', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('class_description', models.CharField(max_length=200)),
                ('class_for', models.CharField(max_length=25)),
                ('timeStamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
