# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_codehubinnovationpostmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehubinnovationpostmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 23, 22, 36, 63515, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codehubinnovationpostmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 12, 23, 22, 44, 652848, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codehubinnovationpostmodel',
            name='vote',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
