# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160406_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehubtopicmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='codehubtopicmodel',
            name='topic_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
