# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_codehubinnovationcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics/'),
        ),
    ]
