# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20160425_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposeEventVoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposeeventmodel',
            name='downVotes',
        ),
        migrations.RemoveField(
            model_name='proposeeventmodel',
            name='upVotes',
        ),
        migrations.AddField(
            model_name='proposeeventvotemodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProposeEventModel'),
        ),
        migrations.AddField(
            model_name='proposeeventvotemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposeeventvotemodel',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfileModel'),
        ),
    ]
