# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_devhubprojectmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devhubprojectmodel',
            name='project_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
