# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_devhubtopiccommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devhubtopiccommentmodel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DevhubTopicModel'),
        ),
    ]
