# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_hostprojectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprojectmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 29, 18, 22, 11, 315715, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostprojectmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 29, 18, 22, 20, 746047, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
