# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_pinghostprojectmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinghostprojectmodel',
            old_name='hosted_event',
            new_name='hosted_project',
        ),
    ]
