# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160501_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinghostprojectmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 1, 18, 45, 12, 300465, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
