# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_messsagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinghostprojectmodel',
            name='ping_status',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
