# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_pinghostprojectmodel_ping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinghostprojectmodel',
            name='ping_status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
