# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hostprojectquestionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposeeventsuggestionmodel',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ProposeEventModel'),
        ),
    ]
