# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20160514_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprojectquestionmodel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.HostProjectModel'),
        ),
    ]
