# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_hostprojectquestionmodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='messsagemodel',
            name='message_status',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='hostprojectquestionmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostProjectModel'),
        ),
    ]
