# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160619_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='messsagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 19, 19, 23, 7, 765974, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
