# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_messsagemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user_profile_pic',
            field=models.FileField(blank=True, default='profile_pics/avatars/default.png', upload_to='profile_pics/'),
        ),
    ]
