# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app', '0031_auto_20160624_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheInfoAddQueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryText', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('queryTags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
