# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20160629_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theinfoaddquerymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theinfoaddquerymodel',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfileModel'),
        ),
    ]
