# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app', '0035_auto_20160629_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedInfoAddQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='taggedquery',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedquery',
            name='tag',
        ),
        migrations.AlterField(
            model_name='theinfoaddquerymodel',
            name='queryTags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='app.TaggedInfoAddQuery', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TaggedQuery',
        ),
        migrations.AddField(
            model_name='taggedinfoaddquery',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TheInfoAddQueryModel'),
        ),
        migrations.AddField(
            model_name='taggedinfoaddquery',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_taggedinfoaddquery_items', to='taggit.Tag'),
        ),
    ]
