# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0038_auto_20160629_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheInfoQueryAnswerVoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='theinfoqueryanswermodel',
            name='answer_vote',
        ),
        migrations.AddField(
            model_name='theinfoqueryanswervotemodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TheInfoQueryAnswerModel'),
        ),
        migrations.AddField(
            model_name='theinfoqueryanswervotemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theinfoqueryanswervotemodel',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfileModel'),
        ),
    ]
