# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20160707_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalquestionmodel',
            old_name='quest_tags',
            new_name='ques_tags',
        ),
    ]
