# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20160708_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralAnswerModel',
            new_name='GeneralQuestionAnswerModel',
        ),
    ]
