# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0042_auto_20160708_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_pic', models.FileField(blank=True, default='group_pics/default_pic_1234.jpg', upload_to='group_pics/')),
                ('group_description', django_markdown.models.MarkdownField()),
                ('group_status', models.CharField(default='active', max_length=15)),
                ('group_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfileModel')),
            ],
        ),
    ]
