# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_creategroupmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateGroupModel',
            new_name='CreateUserGroupModel',
        ),
    ]
