# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20160710_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusergroupmodel',
            name='group_status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
