# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_devhubeventquestionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='views_count',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
