# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_blogpostmodel_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='branch',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='college_year',
            field=models.CharField(default='First Year', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='graduation_year',
            field=models.CharField(default='2017', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='programme',
            field=models.CharField(default='Btech', max_length=15),
        ),
    ]
